### ISSUE TITLE
Importing USFM file does not do full Restore when existing project

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-desktop#734]
I have a USFM that is missing the chapter 2 marker.
When I import that file without a similar existing project, the import works but the chapter 2 text is imported into chapter 1 and chapter 2 is left empty.
When I import that same file with an existing similar project, the import works but the chapter 2 text now appears in both chapter 1 and chapter 2. It technically does not overwrite the entire project as expected.

**Comment by cckozie** [comment]
If I try to import a USFM file that is missing the chapter 1 marker, I get this error message: Error occurred importing project

**Comment by cdwhitfield73** [comment]
Both these issues have been resolved with the new USFM import code.

**Comment by cckozie** [comment]
There still appears to be a problem with overwriting a project with one that has elements missing. The second file in this zip is missing all of chapter 2 (both the chapter markers and all of the verses). If I import the complete file and then import the one missing chapter 2, the resulting project retains the chapter 2 data from the first file. In an "overwrite" I would expect chapter 2 to be blank.
php_usfm (2).zip

**Comment by cdwhitfield73** [comment]
Ok.  I got it this time!  USFM import will always overwrite correctly.

**Comment by cckozie** [comment]
Works as expected now.
